"""updated student model

Revision ID: 23cd3a6c2b0a
Revises: cbcb4ccdaa8f
Create Date: 2023-04-22 04:15:25.706054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cd3a6c2b0a'
down_revision = 'cbcb4ccdaa8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
